### ISSUE TITLE
errno -4058: This is related to npm not being able to find a file.

### ISSUE THREAD

**Issue by tho2622003** [LasTechLabs/LoLXD#1]
Got this error while running npm install. Already had NodeJS and added to PATH, so idk what's the issue here.

![image](https://user-images.githubusercontent.com/100546882/230891466-8ed8662c-a29d-48b7-877e-789cdda21410.png)

Here's the log: 

[2023-04-10T11_14_56_069Z-debug-0.log](https://github.com/LasTechLabs/LoLXD/files/11190130/2023-04-10T11_14_56_069Z-debug-0.log)

**Comment by guidovdijk** [comment]
I believe it is an issue with Git.

`Error: An unknown git error occurred`, `error syscall spawn git` -> it cannot find Git.

Check if Git is installed by running `git --version` in your command line, otherwise install it.
If you already installed it, check if it is available in your `PATH` environment variable.

**Comment by tho2622003** [comment]
That solves it. Thank you!
